### ISSUE TITLE
Group members not loaded when using back button to return to the page

### ISSUE THREAD

**Issue by sinipessala** [NatLibFi/Skosmos#218] opened 2015-03-13 09:06 UTC
## At which URL did you encounter the problem?
http://finto.fi/yso/fi/groups/p26564

## What steps will reproduce the problem?
1. Click "Ryhmät" tab
2. Return to the original page using back button of the browser

## What is the expected output? What do you see instead?
Expected:
The group tab would again show the members of the group
Instead:
A list of all groups in the ontology is shown.

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Firefox

**Comment by henriyli** [comment] 2015-03-30 13:57
Unable to reproduce the bug by following these steps, closing for now.

**Closed by henriyli** 2015-03-30 13:57 UTC
Labels: bug
