### ISSUE TITLE
Data type labels should be shown with lang tags

### ISSUE THREAD

**Issue by miguelvaara** [NatLibFi/Skosmos#1229] opened 2021-10-24 18:57 UTC
## What steps will reproduce the problem?
1. Create a datatype and labels for it
2. Define lang tags for the datatype labels
3. Use the created datatype with the literal of your choice
4. Change the language used in the user interface
5. The datatype label is not changed according to the selected language 

The issue extends this PR: https://github.com/NatLibFi/Skosmos/pull/1198

**Comment by osma** [comment] 2022-04-21 06:52
This is a duplicate of #1217. Closing.

**Closed by osma** 2022-04-21 06:52 UTC
Labels: enhancement, size-medium
