### ISSUE TITLE
Hierarchy not visible when viewing Thesaurus arrays

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Skosmos#515] opened 2016-05-11 10:20 UTC
When Thesaurus arrays are viewed, the ontology hiearachy doesn't show up. Also, concepts belonging to this thesaurus array are not shown, when viewing the array.

Example from YSO ontology:

http://finto.fi/yso/fi/page/p9505

**Comment by osma** [comment] 2016-06-20 07:54
Duplicate of #531, which is resolved.

**Closed by osma** 2016-06-20 07:54 UTC
Labels: bug
