### ISSUE TITLE
Switching interface language does not change content language after selecting a concept from the hierarchy

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#410] opened 2015-12-18 12:01 UTC
1. got to http://skosmos.dev.finto.fi/unesco/en
1. switch to "hierarchy" tab
1. click on the first concept entry "Academic achievement"
1. switch the interface language into French

The content language is still "english". The concept page (preferred term, etc.) is still displayed in English.
Expected behavior : content language should switch to french when switching interface language.

This works fine when concept is accessed using the alphabetical index.

**Comment by osma** [comment] 2015-12-18 12:20
The problem is that when clicking on a concept from the hierarchy view, the clang (content language) parameter is set even though it is not necessary (since the UI language is already English and the content language defaults to the UI language). This forces the content language to English and on subsequent pages the content language will be fixed to English unless explicitly changed by the user.

**Comment by henriyli** [comment] 2016-01-21 07:32
I'm not sure what has happened, but I could not reproduce the issue now. Maybe the recent refactorings have fixed this as a side effect?

**Comment by henriyli** [comment] 2016-01-21 07:40
My bad. The hierarchy links force the clang parameter even if it would not be needed.

**Closed** 2016-01-21 07:51 UTC
Labels: bug, needs backport
