### ISSUE TITLE
Apostrophe in the search box becomes &#39; and a double quote becomes &#34;

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#763] opened 2018-04-26 10:50 UTC
## At which URL did you encounter the problem?

http://finto.fi/en/

## What steps will reproduce the problem?
1. Enter an apostrophe in the search box, and hit enter
2.
3.

## What is the expected output? What do you see instead?
The apostrophe is replaced in the search box with "&#39;".
AFAICT, the apostrophe character is properly isnerted in the search query, it is just not displayed well in the search input

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Firefox

**Comment by osma** [comment] 2018-08-21 13:28
This is similar to #763 and should be fixed by PR #764.

**Comment by osma** [comment] 2018-08-22 12:44
PR #764 didn't actually fix this, so reopening.

**Comment by osma** [comment] 2018-08-27 12:49
The problem is that the query string gets HTML-escaped twice: once in request parameter handling (getQueryParam, which uses FILTER_SANITIZE_STRING), the second time by the Twig template. One of these should be skipped.

**Closed** 2018-08-27 12:55 UTC
Labels: bug
