### ISSUE TITLE
Vocabulary search using "0" as the query argument throws an error

### ISSUE THREAD

**Issue by Ohiekkar** [NatLibFi/Skosmos#1260] opened 2022-01-03 14:10 UTC
## At which URL did you encounter the problem?
https://api.finto.fi/rest/v1/ykl/search

## What steps will reproduce the problem?
1. GET https://api.finto.fi/rest/v1/ykl/search?query=0

## What is the expected output? What do you see instead?
As searching by notation is a thing and 0 is a valid notation I would expect the search to work and find this item: http://urn.fi/URN:NBN:fi:au:ykl:0, just like it works with https://api.finto.fi/rest/v1/ykl/search?query=1.

Currently it throws `400 Bad Request : query parameter missing`. I'd assume this comes from php evaluating "0" to false

**Comment by kinow** [comment] 2022-01-04 06:42
I think your analysis of the problem is spot-on @Ohiekkar ! See linked PR for a tentative fix. Thanks!

**Comment by osma** [comment] 2022-01-20 11:51
Thanks for the report, and the quick confirmation and PR @kinow! I believe this affects not just the REST API but also the search in the web UI. Example:

- http://finto.fi/ykl/en/search?q=1 returns 43 results (classes with a notation beginning with 1 - prefix search is implicit here)
- http://finto.fi/ykl/en/search?q=0 returns an empty result

**Comment by osma** [comment] 2022-01-20 12:27
The REST side was fixed in PR #1261 but the web UI search still suffers from the same problem (see above comment). I'm reopening this issue to keep track of the problem on the web UI side.

**Comment by osma** [comment] 2022-01-27 12:12
Like @Ohiekkar mentioned above, the problem stems from PHP evaluating `"0"` to false. For the REST API, it was fixed in #1261 by changing the test in RestController from this: https://github.com/NatLibFi/Skosmos/blob/21796ca213d5333567dfbd1c67938efd4bab74fa/controller/RestController.php#L178

to this: https://github.com/NatLibFi/Skosmos/blob/52e707930df8ab2bb2e8993cc7181e384cfa8163/controller/RestController.php#L178

Now a similar problem still exists on the web UI side - we need to avoid evaluating `$term` (or similar variables/expressions containing the search term) directly and instead do a more careful check of the contents, for example with `isset` and `strlen` as above.

I suspect that at least this test in ConceptSearchParameters needs to be changed as `!$term` will evaluate to true if `$term` is `"0"`: https://github.com/NatLibFi/Skosmos/blob/52e707930df8ab2bb2e8993cc7181e384cfa8163/model/ConceptSearchParameters.php#L71

**Closed** 2022-03-03 13:46 UTC
Labels: bug, REST
